export const staffs = [
  {
    id: 1,
    name: "Lý Thị Bình",
    image: "",
    address: "Tp Hồ Chí Minh",
    dateOfBirth: "12/02/1994",
    gender: "Female",
    phoneNumber: "0905123456",
    office: "Quản lý",
  },
  {
    id: 2,
    name: "Nguyễn Vân Anh",
    image: "",
    address: "Tp Hồ Chí Minh",
    dateOfBirth: "06/05/1996",
    gender: "Female",
    phoneNumber: "0906456753",
    office: "Nhân viên bán hàng",
  },
  {
    id: 3,
    name: "Nguyễn Tuấn Kiệt",
    image: "",
    address: "Tp Biên Hòa, Đồng Nai",
    dateOfBirth: "12/08/1999",
    gender: "Male",
    phoneNumber: "0908123852",
    office: "Nhân viên vận chuyển",
  },
];

/**--------------------------------------------- */
export const customers = [
  {
    id: 1,
    name: "Nguyễn Thị Lan Anh",
    image: "",
    address: "Tp Hồ Chí Minh",
    dateOfBirth: "20/03/2002",
    gender: "Female",
    phoneNumber: "0406050845",
    email: "anhntl02@gmail.com",
  },
  {
    id: 2,
    name: "Trần Đình Cường",
    image: "",
    address: "Tp Thủ Dầu Một",
    dateOfBirth: "20/08/2003",
    gender: "Male",
    phoneNumber: "0906456753",
    email: "cuongtd03@gmail.com",
  },
  {
    id: 3,
    name: "Lê Đình Bá Lộc",
    image: "",
    address: "Tp Biên Hòa, Đồng Nai",
    dateOfBirth: "23/06/2004",
    gender: "Male",
    phoneNumber: "0908123852",
    email: "locldb04@gmail.com",
  },
];

export const products = [
  {
    id: 1,
    name: "Laptop Dell",
    image: "",
    quantity: 100,
    status: true,
    price: 7000000.0,
    sale: 20,
    category: "Đồ điện tử",
  },
  {
    id: 2,
    name: "Bàn ăn mặt gỗ",
    image: "",
    quantity: 200,
    status: true,
    price: 500000.0,
    sale: 50,
    category: "Bàn ăn",
  },
  {
    id: 3,
    name: "Ghế da giả",
    image: "",
    quantity: 0,
    status: false,
    price: 500000.0,
    sale: 0,
    category: "Ghế ngồi",
  },
];
